version: '2'

volumes:
  nextcloud:
  db:
  smtp-conf:

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud:fpm
    links:
      - db
      - cache
      - smtp
    volumes:
      - nextcloud:/var/www/html
    restart: always
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=cache
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=
      - NEXTCLOUD_ADMIN_USER=jsck
      - NEXTCLOUD_ADMIN_PASSWORD=
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.jackhil.de
      - SMTP_HOST=smtp
      - SMTP_PORT=1025
      - SMTP_NAME=nextcloud@jackhil.de
      - SMTP_PASSWORD=
      - MAIL_FROM_ADDRESS=nextcloud@jackhil.de
      - MAIL_DOMAIN=jackhil.de

  smtp:
    image: jsckh/hydroxide-smtp
    volumes:
      - smtp-conf:


  cache:
    image: redis

  web:
    image: nginx
    ports:
      - 8080:80
    links:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - app
