apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-nfs
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: producers.jackhil.de
    path: "/store/nfs"
